apiVersion: backstage.io/v1alpha3
kind: Component
metadata:
  name: ${{ values.name | dump }}
  title: ${{ values.title | dump }}
  description: ${{ values.description | dump}}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
spec:
  type: service
  lifecycle: development
  owener: ${{ values.owner | dump }}
